{% set name = "atomrdf" %}
{% set version = "0.9.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomrdf-{{ version }}.tar.gz
  sha256: b84a703668bfb6ad7a57ba350e54e63f9413f8e7f95494bd44142d0df2e1a33f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - ase
    - rdflib
    - pyyaml
    - python-graphviz
    - networkx
    - pyscal3 >=3.1.12
    - spglib
    - pandas
    - owlready2
    - atomman
    - mp-api
    - sqlalchemy
    - aimsgb
    - pymatgen
    - mendeleev

test:
  imports:
    - atomrdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://atomrdf.pyscal.org
  summary: Ontology based structural manipulation and quering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
