{% set name = "atomrdf" %}
{% set version = "0.11.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/atomrdf-{{ version }}.tar.gz
  sha256: 4b0af5d0fb2b8cecaf3725164eb36140f784fadc69f985d7bdf3a56844793a05

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - ase
    - rdflib
    - pyyaml
    - python-graphviz
    - networkx
    - pyscal3 >=3.1.12
    - spglib
    - pandas
    - owlready2
    - atomman
    - mp-api
    - sqlalchemy
    - aimsgb
    - pymatgen
    - mendeleev

test:
  imports:
    - atomrdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://atomrdf.pyscal.org
  summary: Ontology based structural manipulation and quering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
