{% set name = "atomrdf" %}
{% set version = "0.8.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atomrdf-{{ version }}.tar.gz
  sha256: 5fd8b28fd3a1faf6bc7027d21e5cda0ea923b74b757322dfd906de4ec6e1ad0a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - ase
    - rdflib
    - pyyaml
    - python-graphviz
    - networkx
    - pyscal3 >=3.1.12
    - spglib
    - pandas
    - owlready2
    - atomman
    - mp-api
    - sqlalchemy

test:
  imports:
    - atomrdf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://atomrdf.pyscal.org
  summary: Ontology based structural manipulation and quering
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srmnitc
